FROM golang:1.9-alpine3.6

ENV PROJECT_PATH=/go/src/github.com/brocaar/lora-gateway-bridge
ENV PATH=$PATH:$PROJECT_PATH/build

RUN apk add --no-cache ca-certificates make git bash

RUN mkdir -p $PROJECT_PATH
COPY . $PROJECT_PATH
WORKDIR $PROJECT_PATH

RUN make requirements
